//------------------------------------------------------------------------
// Copyright(c) 2023 Semblance.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"



#define stringOriginalFilename	"MultiTapDelay.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"MultiTapDelay VST3 (64Bit)"
#else
#define stringFileDescription	"MultiTapDelay VST3"
#endif
#define stringCompanyName		"Semblance\0"
#define stringLegalCopyright	"Copyright(c) 2023 Semblance."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
